# Generated by Django 5.1.1 on 2024-10-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('inporgress', 'InProgress'), ('completed', 'Completed')], default='todo', max_length=10),
        ),
    ]
