# Generated by Django 5.1.1 on 2024-10-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'ToDo'), ('inporgress', 'InProgress'), ('deleted', 'Deleted'), ('completed', 'Completed')], default='todo', max_length=10),
        ),
    ]
